wandb_version: 1

IPC:
  desc: null
  value: null
LOG_DIR:
  desc: null
  value: ../Proxy_Anchor/Newlogs
T:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1629807131
    t:
      1:
      - 1
      2:
      - 1
      - 5
      4: 3.8.8
      5: 0.12.0
      8:
      - 5
alpha:
  desc: null
  value: 32
bn_freeze:
  desc: null
  value: 0
dataset:
  desc: null
  value: Inshop
delta:
  desc: null
  value: -0.0
gpu_id:
  desc: null
  value: 1
l2_norm:
  desc: null
  value: 1
lam:
  desc: null
  value: 1.0
loss:
  desc: null
  value: Proxy_Anchor
lr:
  desc: null
  value: 0.0006
lr_decay_gamma:
  desc: null
  value: 0.25
lr_decay_step:
  desc: null
  value: 20
model:
  desc: null
  value: bn_inception
mrg:
  desc: null
  value: 0.1
mrg_lr:
  desc: null
  value: 5.0e-05
mrg_lr_decay_gamma:
  desc: null
  value: 0.5
mrg_lr_decay_step:
  desc: null
  value: 10
nb_epochs:
  desc: null
  value: 60
nb_workers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: adamw
remark:
  desc: null
  value: ''
sz_batch:
  desc: null
  value: 90
sz_embedding:
  desc: null
  value: 512
warm:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 0.0001
weight_lambda:
  desc: null
  value: 0.3
